# encoding: utf-8
---
recipe:
  Rx: openfly
  description: >-
    词库开源的小鹤音形 Rime 配方

install_files: >-
  openfly*.yaml
  lua/openfly*.lua

patch_files:
  default.custom.yaml:
    - patch/+:
        "switcher/save_options/+":
          - "openfly_enable_2nd_short"
        "ascii_composer/switch_key/Shift_L": commit_code
        "ascii_composer/switch_key/Shift_R": commit_code
        "ascii_composer/switch_key/Caps_Lock": noop
